projects:
  - name: Quiz Generator
    environments:
      - name: Dev
        services:
          - type: web
            name: password-generator-frontend-dev
            runtime: static
            repo: https://github.com/SavenkoRodion/scripting-languages-project/tree/be-main/ui/quiz-generator
            buildCommand: cd frontend && npm install && npm run build
            staticPublishPath: ui/quiz-generator/dist
