projects:
  - name: Quiz Generator
    environments:
      - name: Dev
        services:
          - type: web
            name: quiz-generator-frontend-dev
            runtime: static
            buildCommand: cd ui/quiz-generator && npm install && npm run build
            staticPublishPath: ui/quiz-generator/dist
          - type: web
            name: quiz-generator-backend-dev
            runtime: python
            plan: free
            buildCommand: cd be && pip install -r requirements.txt
            startCommand: cd be && gunicorn -w 2 -b 0.0.0.0:$PORT backend.app:app
